config/routes.rb
Rails.application.routes.draw do

  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  #devise_for :users
  root to: 'articles#index'

  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  namespace :admin do
    resource :dashboard
    resource :profile, only: [:edit, :update]
    resources :articles do
      member do
        post :publish
        post :unpublish
      end
    end
    resources :pages
    resources :users do
      member do
        post :uninvite
      end
    end
    namespace :settings do
      resources :categories
    end
  end

  resources :articles
  resources :categories

  get "/:id", to: "pages#show", as: 'page'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here.
    user ||= User.new # guest user (not logged in)
    # a signed-in user can do everything
    if user.has_role? :admin
     # an admin can do everything
      can :manage, :all
    elsif user.has_role? :edit
        can :manage, Article
    elsif user.has_role? :author
      # an editor can do everything to documents and reports
      can :index, [Article]
      can :create, [Article]
      can :update, [Article] do |article|
        article.try(:user) == user
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessor :image

  belongs_to :user
  belongs_to :category

  has_many :comments

  validates :title, :body, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image

  def published?
    return false if published_at.nil?
    published_at < Time.now
  end

  def publish!
    update_attribute(:published_at, Time.now)
  end

  def unpublish!
    update_attribute(:published_at, nil)
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessor :image

  has_many :articles

  validates :name, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :image

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :article

end

app/models/concerns/invitable.rb
module Invitable

  def invited?
   !self.invitation_token.nil?
  end

  def accepted_invitation?
    !self.invitation_token.nil? && !self.invitation_accepted_at.nil?
  end

end

app/models/concerns/socialble.rb
module Sociable

  SOCIAL_NETWORKS = {
    twitter: "twitter_handle",
    google_plus: "google_plus_url",
    linked_in: "linked_in_url"
  }

  SOCIAL_NETWORKS.each do |key, value|
    define_method("#{key}?")  do
      if send(:value).nil?
        return false
      else
        return true
      end
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

  UNDELETABLE_PAGES = %w(contact about)

  belongs_to :user

  validates :title, :body, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged


  def can_be_deleted?
    UNDELETABLE_PAGES.include?(slug) ? false : true
  end



end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base

  include RoleModel

  include Invitable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :invitable, :async

  has_many :articles

  validates :name, presence: true
  validates :email, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  roles :admin, :editor, :author, :user

  scope :invited, -> { where("encrypted_password=''") }
  scope :accepted, -> { where("encrypted_password !=''") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || admin_dashboard_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  decorates_assigned :article

  def index
    @articles = Article.all.decorate
  end

  def show
    @article = Article.friendly.find(params[:id]).decorate
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])
    @articles = @category.articles.decorate
    render template: 'articles/index'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @page = Page.friendly.find(params[:id])
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

end

app/helpers/application_helper.rb
require 'kramdown'

module ApplicationHelper

  def markdown(text)
    Kramdown::Document.new(text).to_html.html_safe
  end

  def navigation_link(name, url)
    class_name = active_class_name(url)
    link = link_to(name, url)
    content_tag(:li, link, class: class_name)
  end

  def admin_sidebar_item(link, title, icon)
    Rails.logger.debug("path is #{request.path}")
    class_name = active_class_name(link)
    span_text = content_tag(:span, title, class: 'item-text')
    icon = content_tag(:em, "", class: "fa fa-#{icon}")
    link = content_tag(:a, raw("#{icon} #{span_text}"), class: 'no-submenu', title: title, href: link)
    content_tag(:li, raw(link), class: class_name)
  end

  def admin_sidebar_submenu_item(link, title)
    class_name = active_class_name(link)
    link = content_tag(:a, title, href: link, class: 'no-submenu', title: title)
    content_tag(:li, raw(link), class: class_name)
  end

  def active_class_name(link)
    return 'active' if request.path == link
    class_name = request.path.split('/').include?(link.split('/').last) ? "active" : ""
    return class_name
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper


  def article_title(article)
    content_tag :h3, article_link(article, article.title)
  end

  def article_link(article, link_text)
    link_to link_text, article_path(article)
  end

  def article_preview(article)
    markdown(truncate(article.preview, {length: 287, omission: ' [...]'}))
  end

  def category_link(category)
    content_tag :div, category_link(article.category)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/_form.html.haml
= form_for [:admin, @page], role: 'form' do |f|
  .form-group.form-group-lg
    %label Title
    = f.text_field :title, class: 'form-control input-lg', placeholder: 'Title'
  .form-group
    %label Body
    = f.text_area :body, data: {"uk-markdownarea" => "{mode: 'tab'}"}
  %fieldset.text-right
    = link_to "Cancel", admin_pages_path, class: "btn btn-default"
    = f.submit 'Save', class: 'btn btn-purple'

app/views/admin/pages/_page.html.haml
%td.col-sm-1= page.id
%td.col-sm-4= page.title
%td.col-sm-2= "/#{page.slug}"
%td.col-sm-1= page.user.name
%td.col-sm-2= page.created_at.to_formatted_s(:us_format)
%td.col-sm-4
  - if can?(:edit, page)
    = link_to raw("<span class='fa fa-edit'></span> Edit"), edit_admin_page_path(page), class: 'button btn btn-xs btn-purple'
  - if can?(:delete, page) && page.can_be_deleted?
    = link_to raw("<span class='fa fa-ban'></span> Delete"), admin_page_path(page), class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?'}

app/views/admin/pages/edit.html.haml
%h3 Edit Page - #{@page.title}
= render partial: 'form'

app/views/admin/pages/index.html.haml
.pull-right
  = link_to raw("<span class='fa fa-plus'></span> New Page"), new_admin_page_path, class: 'btn btn-purple'

%h3 All Pages

.table-responsive.table.bordered.col-md-12
  %table.table-striped.col-md-12
    %thead
      %tr
        %th #
        %th Title
        %th URL
        %th Author
        %th Created At
        %th Tasks
    %tbody
      - @pages.each do |page|
        %tr.danger
          = render partial: page

app/views/admin/pages/new.html.haml
%h3 New Page
= render partial: 'form'

app/views/layouts/admin.html.haml
!!!
/[if lt IE 7] <html class="ie ie6 lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="ie ie7 lt-ie9 lt-ie8"        lang="en">
/[if IE 8] <html class="ie ie8 lt-ie9"               lang="en">
/[if IE 9] <html class="ie ie9"                      lang="en">
/ [if !IE]><!
%html.no-ie{:lang => "en"}
  / <![endif]
  %head
    / Meta
    %meta{:charset => "utf-8"}/
    %title Quark Admin
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9] <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script><script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
  %body
    .wrapper
      = render partial: 'layouts/admin/header'
      = render partial: 'layouts/admin/sidebar'
      %section
        .content-wrapper
          = yield
    = javascript_include_tag 'admin/theme', 'admin/pages'

app/views/layouts/admin/_header.html.haml
%nav.navbar.navbar-default.navbar-top.navbar-fixed-top{:role => "navigation"}
  .navbar-header
    %a.navbar-brand{:href => "index.html"}
      .brand-logo
        %span.atom ⚛
        Quark
      .brand-logo-collapsed
        .span.atom ⚛
  .nav-wrapper
    %ul.nav.navbar-nav
      %li
        %a.hidden-xs{data: {"toggle-state" => "aside-collapsed"}, href: "#", title: 'Collapse Menu'}
          %em.fa.fa-navicon
        %a.visible-xs{"data-toggle-state" => "aside-toggled", :href => "#"}
          %em.fa.fa-navicon
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to raw('<i class="fa fa-user"></i> Edit Profile'), edit_admin_profile_path, title: 'Edit Profile'
      %li
        = link_to raw("<i class='fa fa-power-off'></i> Log Out"), destroy_user_session_path, method: :delete, title: 'Log Out'

app/views/layouts/admin/_sidebar.html.haml
%aside.aside
  %nav.sidebar
    .item.user-block
      .user-block-picture
        .user-block-status
          %img.img-thumbnail.img-circle{:alt => "Avatar", :height => "60", :src => gravatar_image_url(current_user.email), :width => "60"}/
          .circle.circle-success.circle-lg
      .user-block-info
        %span.user-block-name.item-text Welcome User
        %span.user-block-role= current_user.name.split(' ').first
    %ul.nav
      %li.nav-heading Main navigation
      = admin_sidebar_item("/admin/dashboard", "Dashboard", "dot-circle-o")
      = admin_sidebar_item("/admin/articles", "Articles", "edit")
      = admin_sidebar_item("/admin/pages", "Pages", "flask")
      = admin_sidebar_item("/admin/users", "Users", "users")
      - if params[:controller].split('/').include?('settings')
        %li.active
          %a.no-submenu{"data-toggle" => "collapse-next", :href => "/admin/settings", :title => "Settings"}
            %em.fa.fa-cogs
            %span.item-text Settings
            %ul.nav
              = admin_sidebar_submenu_item(admin_settings_categories_path, "Categories")
      - else
        %li
          %a.no-submenu{"data-toggle" => "collapse-next", :href => "/admin/settings", :title => "Settings"}
            %em.fa.fa-cogs
            %span.item-text Settings
            %ul.nav.collapse
              = admin_sidebar_submenu_item(admin_settings_categories_path, "Categories")

app/views/layouts/application.html.haml
!!!
/[if lt IE 7] <html class="ie ie6 lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="ie ie7 lt-ie9 lt-ie8"        lang="en">
/[if IE 8] <html class="ie ie8 lt-ie9"               lang="en">
/[if IE 9] <html class="ie ie9"                      lang="en">
/ [if !IE]><!
%html.no-ie{:lang => "en"}
  / <![endif]
  %head
    / Meta
    %meta{:charset => "utf-8"}/
    %title NurdGurls
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{href: 'http://fonts.googleapis.com/css?family=Crushed|PT+Sans+Narrow:400,700|Neucha|Istok+Web:400,700|Exo:400,700|Grand+Hotel|Englebert|Montserrat|Exo+2:700|Roboto+Condensed:400,700|Roboto:400,700', rel: 'stylesheet', type: 'text/css'}
    %link{href: 'http://fonts.googleapis.com/css?family=Lora|Open+Sans|Montserrat', rel: 'stylesheet', type: 'text/css'}
  %body
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation", style: 'border: 0px;'}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"}
            #logo.pull-left NG
            .brand-text{style: "margin-left: 20px; margin-top: 10px;"}
              .name
                <span class='upper'>N</span>urd <span class='upper'>G</span>urls
              .tagline{style: "margin-top: 20px; font-size: 0.4em; font-family: 'PT Sans Narrow'"} Facts don't see gender; too bad, because we're gorgeous!
        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            = navigation_link("Home", "/")
            = navigation_link("About", "/about")
            = navigation_link("Contact", "/contact")
    %section.container-fluid
      .col-sm-12
        = yield
    .clearfix
    %footer
      .footer-above
        .background
        .container
          .row
            .footer-col.col-md-3
              %h3 Categories
              %ul
                - Category.all.each do |category|
                  %li
                    = link_to category.name, category_path(category.slug)
            .footer-col.col-md-3
              %h3 Archive
              %ul
                %li
                  %a{href: '#'} August 2014
                %li
                  %a{href: '#'} July 2014
                %li
                  %a{href: '#'} June 2014
                %li
                  %a{href: '#'} May 2014
            .footer-col.col-md-3
              %h3 Meta
              %ul
                %li
                  %a{href: '#'} Sign Up
                %li
                  %a{href: '#'} Log In
                %li
                  %a{href: '#'} Contribute

app/views/layouts/login.html.haml
!!!
/[if lt IE 7] <html class="ie ie6 lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="ie ie7 lt-ie9 lt-ie8"        lang="en">
/[if IE 8] <html class="ie ie8 lt-ie9"               lang="en">
/[if IE 9] <html class="ie ie9"                      lang="en">
/ [if !IE]><!
%html.no-ie{:lang => "en"}
  / <![endif]
  %head
    / Meta
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0", :name => "viewport"}/
    %title BeAdmin - Bootstrap Admin Theme
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9] <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script><script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    / START wrapper
    .row.row-table.page-wrapper
      .col-lg-3.col-md-6.col-sm-8.col-xs-12.align-middle
        / START panel
        .panel.panel-dark.panel-flat{"data-offset" => "0", "data-play" => "fadeIn", "data-toggle" => "play-animation"}
          .panel-heading.text-center
            %a{:href => "#"}
              %span.atom ⚛
              Quark
          .panel-body
            = yield
        / END panel
    / END wrapper
    / START Scripts
    / Main vendor Scripts
    = javascript_include_tag 'animo.min.js', 'pages'

app/views/pages/show.html.haml
.containter-fluid
  .row
    .col-sm-12
      .col-sm-7
        %article
          %h3
            %a= @page.title
          = markdown(@page.body)