config/routes.rb
Rails.application.routes.draw do

  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  #devise_for :users
  root to: 'articles#index'

  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  namespace :admin do
    resource :dashboard
    resource :profile, only: [:edit, :update]
    resources :articles do
      member do
        post :publish
        post :unpublish
      end
    end
    resources :pages
    resources :users do
      member do
        post :uninvite
      end
    end
    namespace :settings do
      resources :categories
    end
  end

  resources :articles
  resources :categories

  get "/:id", to: "pages#show", as: 'page'

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessor :image

  belongs_to :user
  belongs_to :category

  has_many :comments

  validates :title, :body, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image

  def published?
    return false if published_at.nil?
    published_at < Time.now
  end

  def publish!
    update_attribute(:published_at, Time.now)
  end

  def unpublish!
    update_attribute(:published_at, nil)
  end

end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::BaseController

    #load_and_authorize_resource find_by: :slug
    before_filter :find_or_new_article, except: 'index'

    def index
      @articles = Article.includes(:user).all
    end

    def show; end

    def new; end

    def create
      Rails.logger.debug("artickel is #{params[:article]}")
      @article.attributes = article_params
      @article.user = current_user
      if @article.save
        flash[:notice] = "Article Created"
        redirect_to admin_articles_path
      else
        render action: 'new'
      end
    end

    def edit; end

    def update
      @article.attributes = article_params
      if @article.save
        redirect_to admin_articles_path
      else
        render action: 'edit'
      end
    end

    def publish
      if @article.publish!
        flash[:notice] = "Article - #{@article.title} published"
        redirect_to admin_articles_path
      end
    end

    def unpublish
      if @article.unpublish!
        flash[:notice] = "Article - #{@article.title} unpublished"
        redirect_to admin_articles_path
      end
    end

    def destroy
      if @article.destroy
        flash[:notice] = "Article - #{@article.title} deleted"
        redirect_to admin_articles_path
      end
    end

    private

    def find_or_new_article
      @article = params[:id] ? Article.friendly.find(params[:id]) : Article.new
    end

    def article_params
      Rails.logger.debug("Parmas are #{params}")
      params.require(:article).permit(:title, :preview, :body, :featured, :category_id, :image, :published_at)
    end

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  decorates_assigned :article

  def index
    @articles = Article.all.decorate
  end

  def show
    @article = Article.friendly.find(params[:id]).decorate
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper


  def article_title(article)
    content_tag :h3, article_link(article, article.title)
  end

  def article_link(article, link_text)
    link_to link_text, article_path(article)
  end

  def article_preview(article)
    markdown(truncate(article.preview, {length: 287, omission: ' [...]'}))
  end

  def category_link(category)
    content_tag :div, category_link(article.category)
  end
end

app/views/admin/articles/_article.html.haml
%td.col-sm-1= article.id
%td.col-sm-4= article.title
%td.col-sm-1= article.user.name
%td.col-sm-2= article.created_at.to_formatted_s(:us_format)
- if article.published?
  %td.col-sm-2= article.published_at.to_formatted_s(:us_format)
- else
  %td.col-sm-2

%td.col-sm-4
  - if can?(:edit, article) && !article.published?
    = link_to raw("<span class='fa fa-edit'></span> Edit"), edit_admin_article_path(article), class: 'button btn btn-xs btn-purple'
  - if can?(:delete, article) && !article.published?
    = link_to raw("<span class='fa fa-ban'></span> Delete"), admin_article_path(article), class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?'}
  - if can?(:publish, article)
    - unless article.published?
      = link_to raw("<span class='fa fa-bolt'></span> Publish"), publish_admin_article_path(article), method: :post, class: 'btn btn-xs btn-warning'
    - else
      = link_to "Unpublish", unpublish_admin_article_path(article), method: :post, class: 'btn btn-xs btn-warn', data: {confirm: true}

app/views/admin/articles/_form.html.haml
= form_for [:admin, @article], role: 'form', multipart: true do |f|
  .form-group.form-group-lg
    %label Title
    = f.text_field :title, class: 'form-control input-lg', placeholder: 'Title'
  .form-group
    %label Preview
    = f.text_area :preview, class: 'form-control'
  .form-group
    %label Body
    = f.text_area :body, data: {"uk-markdownarea" => "{mode:'tab'}"}
  %h4 Meta Information
  .form-group
    .row
      .col-md-4
        .datetimepicker.date.mb-lg.input-group
          = f.text_field :published_at, class: 'form-control', placeholder: 'Publish On'
          %span.input-group-addon
            %span.fa-calendar.fa
      .col-md-4
        %label Feature
        = f.check_box :featured
      .col-md-4
        %label Category
        = f.select :category_id, Category.all.collect { |c| [c.name, c.id] }
    .row
      .col-md-8
        %label Header Image
        = f.file_field :image

  .clearfix
  %fieldset.text-right
    = link_to "Cancel", admin_articles_path, class: 'btn btn-default'
    = f.submit 'Save', class: 'btn btn-purple'

app/views/admin/articles/edit.html.haml
%h3 Edit Article - #{@article.title}
= render partial: 'form'

app/views/admin/articles/index.html.haml
.pull-right
  = link_to raw("<span class='fa fa-plus'></span> New Article"), new_admin_article_path, class: 'btn btn-purple'
%h3 All Articles

.table-responsive.table.bordered.col-md-12
  %table.table-striped.col-md-12
    %thead
      %tr
        %th #
        %th Title
        %th Author
        %th Created At
        %th Published At
        %th Tasks
    %tbody
      - @articles.each do |article|
        %tr.danger
          = render partial: article

app/views/admin/articles/new.html.haml
%h3 New Article
= render partial: 'form'