config/routes.rb
Rails.application.routes.draw do

  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  #devise_for :users
  root to: 'articles#index'

  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  namespace :admin do
    resource :dashboard
    resource :profile, only: [:edit, :update]
    resources :articles do
      member do
        post :publish
        post :unpublish
      end
    end
    resources :pages
    resources :users do
      member do
        post :uninvite
      end
    end
    namespace :settings do
      resources :categories
    end
  end

  resources :articles
  resources :categories

  get "/:id", to: "pages#show", as: 'page'

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessor :image

  has_many :articles

  validates :name, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :image

end

app/controllers/admin/settings/base_controller.rb
module Admin
  module Settings
    class BaseController < ApplicationController

      before_filter :authenticate_user!
      before_filter :verify_admin

      layout 'admin'

      private

      def verify_admin
        return true
      end

    end
  end
end

app/controllers/admin/settings/categories_controller.rb
module Admin
  module Settings
    class CategoriesController < BaseController

      before_filter :find_or_new_category, except: [:index]

      def index
        @categories = Category.all
      end

      def new; end

      def create
        @category.attributes = allowed_params
        if @category.save
          redirect_to admin_settings_categories_path
        else
          render action: :new
        end
      end

      def edit; end

      def update
        @category.attributes = allowed_params
        if @category.save
          redirect_to admin_settings_categories_path
        else
          render action: :edit
        end
      end

      def destroy
        if @category.articles.size == 0
          if @category.destroy
            redirect_to admin_settings_categories_path
          end
        else
          flash[:error] = "Category has posts and cannot be deleted"
          redirect_to admin_settings_categories_path
        end
      end

      private

      def find_or_new_category
        @category = params[:id] ? Category.friendly.find(params[:id]) : Category.new
      end

      def allowed_params
        params.require(:category).permit(:name, :image)
      end

    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])
    @articles = @category.articles.decorate
    render template: 'articles/index'
  end

end

app/helpers/admin/settings/categories_helper.rb
module Admin::Settings::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/settings/categories/_category.html.haml
%td.col-sm-1= category.id
%td.col-sm-4
  - unless category.image.nil?
    = image_tag(category.image.url, class: 'thumbnail', style: "max-width: 100px; max-height: 75px;")
  = category.name
%td.col-sm-1= category.articles.size
%td.col-sm-2= category.created_at.to_formatted_s(:us_format)
%td.col-sm-4
  - if can?(:edit, category)
    = link_to raw("<i class='fa fa-edit'></i> Edit"), edit_admin_settings_category_path(category), class: 'btn btn-purple'
  - if can?(:delete, category) && category.articles.size == 0
    = link_to raw("<i class='fa fa-ban'></i> Delete"), admin_settings_category_path(category), class: 'btn btn-danger', data: {method: :delete, confirm: 'Are you sure?'}

app/views/admin/settings/categories/_form.html.haml
= simple_form_for [:admin, :settings, @category] do |f|
  = f.input :name
  = f.input :image, as: :file
  .actions
    = f.submit "Save Category"

app/views/admin/settings/categories/edit.html.haml
%h3 Settings &raquo; Edit Category
= render partial: 'form'

app/views/admin/settings/categories/index.html.haml
.pull-right
  = link_to raw("<i class='fa fa-plus'></i> New Category"), new_admin_settings_category_path, class: 'btn btn-purple'
%h3 Settings &raquo; Categories

.table-responsive.table.table.bordered.col-md-12
  %table.table.striped.col-md-12
    %thead
      %tr
        %th #
        %td Name
        %td Num Articles
        %td Created At
        %td Tasks
    %tbody
      - @categories.each do |category|
        %tr
          = render partial: category

app/views/admin/settings/categories/new.html.haml
%h3 Settings &raquo; New Category
= render partial: 'form'