config/routes.rb
Rails.application.routes.draw do

  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  #devise_for :users
  root to: 'articles#index'

  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  namespace :admin do
    resource :dashboard
    resource :profile, only: [:edit, :update]
    resources :articles do
      member do
        post :publish
        post :unpublish
      end
    end
    resources :pages
    resources :users do
      member do
        post :uninvite
      end
    end
    namespace :settings do
      resources :categories
    end
  end

  resources :articles
  resources :categories

  get "/:id", to: "pages#show", as: 'page'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here.
    user ||= User.new # guest user (not logged in)
    # a signed-in user can do everything
    if user.has_role? :admin
     # an admin can do everything
      can :manage, :all
    elsif user.has_role? :edit
        can :manage, Article
    elsif user.has_role? :author
      # an editor can do everything to documents and reports
      can :index, [Article]
      can :create, [Article]
      can :update, [Article] do |article|
        article.try(:user) == user
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessor :image

  belongs_to :user
  belongs_to :category

  has_many :comments

  validates :title, :body, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image

  def published?
    return false if published_at.nil?
    published_at < Time.now
  end

  def publish!
    update_attribute(:published_at, Time.now)
  end

  def unpublish!
    update_attribute(:published_at, nil)
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessor :image

  has_many :articles

  validates :name, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :image

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :article

end

app/models/concerns/invitable.rb
module Invitable

  def invited?
   !self.invitation_token.nil?
  end

  def accepted_invitation?
    !self.invitation_token.nil? && !self.invitation_accepted_at.nil?
  end

end

app/models/concerns/socialble.rb
module Sociable

  SOCIAL_NETWORKS = {
    twitter: "twitter_handle",
    google_plus: "google_plus_url",
    linked_in: "linked_in_url"
  }

  SOCIAL_NETWORKS.each do |key, value|
    define_method("#{key}?")  do
      if send(:value).nil?
        return false
      else
        return true
      end
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

  UNDELETABLE_PAGES = %w(contact about)

  belongs_to :user

  validates :title, :body, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged


  def can_be_deleted?
    UNDELETABLE_PAGES.include?(slug) ? false : true
  end



end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base

  include RoleModel

  include Invitable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :invitable, :async

  has_many :articles

  validates :name, presence: true
  validates :email, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  roles :admin, :editor, :author, :user

  scope :invited, -> { where("encrypted_password=''") }
  scope :accepted, -> { where("encrypted_password !=''") }

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController

    before_filter :find_or_new_user, except: [:index]

    def index
      @users = User.accepted
      @invited_users = User.invited
    end

    def show; end

    def new; end

    def create
      if User.invite!(invite_user_params, current_user)
        flash[:notice] = "User - #{@user.name} has been invited"
        redirect_to admin_users_path
      else
        render action: :new
      end
    end

    def edit; end

    def update
      @user.attributes = user_params
      if @user.save
        flash[:notice] = "User - #{@user.name} updated"
        redirect_to admin_users_path
      else
        redner action: :edit
      end
    end

    def destroy
      if @user.destroy
        flash[:notice] = "User - #{@user.name} deleted"
        redirect_to admin_users_path
      end
    end

    private

    def invite_user_params
      params.require(:user).permit(:name, :email, :roles)
    end

    def user_params
      params.require(:user).permit(:name, :email, :twitter_handle,
                                   :linked_in_ur, :google_plus_url, :roles,
                                   :bio, :short_bio)
    end


    def find_or_new_user
      @user = params[:id] ? User.friendly.find(params[:id]) : User.new
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || admin_dashboard_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  decorates_assigned :article

  def index
    @articles = Article.all.decorate
  end

  def show
    @article = Article.friendly.find(params[:id]).decorate
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])
    @articles = @category.articles.decorate
    render template: 'articles/index'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @page = Page.friendly.find(params[:id])
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
require 'kramdown'

module ApplicationHelper

  def markdown(text)
    Kramdown::Document.new(text).to_html.html_safe
  end

  def navigation_link(name, url)
    class_name = active_class_name(url)
    link = link_to(name, url)
    content_tag(:li, link, class: class_name)
  end

  def admin_sidebar_item(link, title, icon)
    Rails.logger.debug("path is #{request.path}")
    class_name = active_class_name(link)
    span_text = content_tag(:span, title, class: 'item-text')
    icon = content_tag(:em, "", class: "fa fa-#{icon}")
    link = content_tag(:a, raw("#{icon} #{span_text}"), class: 'no-submenu', title: title, href: link)
    content_tag(:li, raw(link), class: class_name)
  end

  def admin_sidebar_submenu_item(link, title)
    class_name = active_class_name(link)
    link = content_tag(:a, title, href: link, class: 'no-submenu', title: title)
    content_tag(:li, raw(link), class: class_name)
  end

  def active_class_name(link)
    return 'active' if request.path == link
    class_name = request.path.split('/').include?(link.split('/').last) ? "active" : ""
    return class_name
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper


  def article_title(article)
    content_tag :h3, article_link(article, article.title)
  end

  def article_link(article, link_text)
    link_to link_text, article_path(article)
  end

  def article_preview(article)
    markdown(truncate(article.preview, {length: 287, omission: ' [...]'}))
  end

  def category_link(category)
    content_tag :div, category_link(article.category)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @user], role: :form do |f|
  .row
    .form_group
      .col-md-6
        = f.input :first_name
      .col-md-6
        = f.input :last_name
  .row
    .form_group
      .col-md-6
        = f.input :email
  .row
    .form_group
      .col-md-6
        = f.input :password
      .col-md-6
        = f.input :password_confirmation

app/views/admin/users/_user.html.haml
%td.col-sm-1= user.id
%td.col-sm-3= link_to user.name, admin_user_path(user)
%td.col-sm-1= user.email
%td.col-sm-2= user.roles.to_a.join(', ')
%td.col-sm-2
  - unless user.encrypted_password.nil?
    = user.created_at.to_formatted_s(:us_format)
  - else
    = user.invitation_created_at.to_formatted_s(:us_format)
%td.col-sm-2
  = link_to raw("<span class='fa fa-edit'></span> Edit</span>"), edit_admin_user_path(user), class: 'button btn btn-xs btn-purple'
  - if user.invited? && !user.accepted_invitation?
    = link_to raw("<span class='fa fa-ban'></span> Uninvite</span>"), admin_user_path(user), class: 'button btn btn-xs btn-danger', method: :delete

app/views/admin/users/edit.html.haml
%h3 Edit User - #{@user.name}
= simple_form_for [:admin, @user], url: admin_user_path, html: {class: 'form form-horizontal'}, role: :form do |f|
  .form_group
    = f.input :name
  .form_group
    = f.input :email
  .form_group
    = f.input :twitter_handle
  .form_group
    = f.input :linked_in_url, placeholder: 'http://www.linkedin.com/in/your_username/'
  .form_group
    = f.input :google_plus_url, placeholder: 'http://google.com/+JimRayjimiray'
  .form_group
    = f.input :short_bio, placeholder: 'Please right a little about yourself', as: :text, label: "Short Bio"
  .form_group
    = f.input :bio, input_html: {data: {"uk-markdownarea" => "{mode:'tab'}"}}
  %fieldset.text-right
    = link_to "Cancel", admin_articles_path, class: 'btn btn-default'
    = f.submit 'Save', class: 'btn btn-purple'

app/views/admin/users/index.html.haml
.pull-right
  = link_to raw("<span class='fa fa-plus'></span> Invite User"), new_admin_user_path, class: 'btn btn-purple'
%h3 Users

.table-responsive.table.bordered.col-md-12
  %table.table-striped.col-md-12
    %thead
      %tr
        %th #
        %th Name
        %th Email
        %th Roles
        %th Member Since
        %th Tasks
    %tbody
      - @users.each do |user|
        %tr.danger
          = render partial: user

%br
%br

%h3 Invited Users
.table-responsive.table.bordered.col-md-12
  %table.table-striped.col-md-12
    %thead
      %tr
        %th #
        %th Name
        %th Email
        %th Roles
        %th Invited On
        %th Tasks
    %tbody
      - @invited_users.each do |user|
        %tr.danger
          = render partial: user

app/views/admin/users/new.html.haml
%h3 Invite A User

= simple_form_for [:admin, @user] do |f|
  .row
    .col-md-6
      = f.input :name
  .row
    .col-md-6
      = f.input :roles, collection: User.valid_roles
  .row
    .col-md-6
      = f.input :email

  %fieldset.text-right
    = link_to "Cancel", admin_articles_path, class: 'btn btn-default'
    = f.submit 'Invite User', class: 'btn btn-purple'

app/views/admin/users/show.html.haml
.pull-right
  = link_to raw("<span class='fa fa-pencil'></span> Edit"), edit_admin_user_path(@user), class: 'btn btn-purple'
  = link_to raw("<span class='fa fa-trash-o'></span> Disable"), admin_user_path(@user), class: 'btn btn-danger', data: {confirm: "Are you sure?"}, method: :delete
%h3 User - #{@user.name}